default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: PAA_development 
  #username: root
  #password: root

test:
  <<: *default
  database: PAA_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>